---
name: Release Please

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  release-please:
    permissions:
      id-token: write # to enable use of OIDC for npm provenance
      # permissions for pushing commits and opening PRs are handled by the `generate-token` step
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@32691ba7c9e7063bd457bd8f2a5703138591fa58 # v1
        id: generate-token
        with:
          app_id: ${{ secrets.ECOSCRIPT_APP_ID }}
          private_key: ${{ secrets.ECOSCRIPT_APP_PRIVATE_KEY }}
      # This action will create a release PR when regular conventional commits are pushed to main, it'll also detect if a release PR is merged and npm publish should happen
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: node
          token: ${{ steps.generate-token.outputs.token }}

      # Publish to NPM on new releases
      - uses: actions/checkout@v4
        if: ${{ steps.release.outputs.releases_created }}
      - uses: pnpm/action-setup@v2
        if: ${{ steps.release.outputs.releases_created }}
      - uses: actions/setup-node@v4
        if: ${{ steps.release.outputs.releases_created }}
        with:
          cache: pnpm
          node-version: lts/*
          registry-url: 'https://registry.npmjs.org'
      - run: corepack enable && pnpm --version && pnpm install
        if: ${{ steps.release.outputs.releases_created }}
      - name: Set publishing config
        run: pnpm config set '//registry.npmjs.org/:_authToken' "${NODE_AUTH_TOKEN}"
        if: ${{ steps.release.outputs.releases_created }}
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_PUBLISH_TOKEN}}
      # Release Please has already incremented versions and published tags, so we just
      # need to publish the new version to npm here
      - run: pnpm publish
        if: ${{ steps.release.outputs.releases_created }}
        env:
          NPM_CONFIG_PROVENANCE: true
      # Publish to GitHub Pages
      - run: pnpm build:demo
        if: ${{ steps.release.outputs.releases_created }}
      - uses: peaceiris/actions-gh-pages@373f7f263a76c20808c831209c920827a82a2847 # v3
        if: ${{ steps.release.outputs.releases_created }}
        with:
          github_token: ${{ steps.generate-token.outputs.token }}
          publish_dir: ./demo/dist
